apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  app.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            proxy_pass http://webapp-service;
        }
    }
